### ISSUE TITLE
It's not taking symbols, only alphanumeric characters are displayed.

### ISSUE THREAD

**Issue by amanksdotdev** [bannyvishwas2020/MyHandWriting#1]
Special characters and symbols are not being displayed only alphanumeric characters are. Also I'm having trouble printing it, stuck in loading preview.

**Comment by bannyvishwas** [comment]
ya bro.. only limited no. of symbols. You can create new symbols and crop them, remove background and place them in the set0/others/ directory and give the image name as it's ord() value.
i.e. ord('?')-> 63 ,so the file name will be 63.png.
I did't include more symbols as it was delaying this repository to be uploaded. Now you can contribute to this. Add more symbols.. 
And about that loading screen .. it may be because of filter property in CSS. which is actually taking more time to process each letter to convert in into black letter.
You can remove letter_color parameter from the program just then it will be printed. thankss

**Comment by bannyvishwas** [comment]
So I added black and blue fonts separate to the letter set0 and updated the script to adopt the changes. so.. now we need not to filter each letter ..
Now you can print in pdf without stucking into the loading screen.
Thanks..
